<?php

namespace Database\Seeders;

use App\Models\Guru;
use Illuminate\Database\Seeder;

class GuruSeeder extends Seeder
{
    public function run(): void
    {
        $gurus = [
            [
                'id' => 2,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ali Murtadho,S.Pd',
                'kategori' => 'SMP',
                'mapel_bidang' => 'Seni Budaya',
                'pendidikan' => 'S1 Senirupa Terapan UNESA',
                'status' => 'Aktif',
                'alamat' => 'JL Pesantren',
                'created_at' => '2026-06-03 03:42:56',
                'updated_at' => '2026-06-16 18:33:17',
            ],
            [
                'id' => 3,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Muhajir, S.Pd.I',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Kepala Sekolah',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => 'JL Pesantren',
                'created_at' => '2026-06-03 03:42:56',
                'updated_at' => '2026-07-14 23:40:20',
            ],
            [
                'id' => 4,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Sapto Cahyono, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Bimbingan dan Konseling',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => 'Sumursongo',
                'created_at' => '2026-07-14 23:49:54',
                'updated_at' => '2026-07-14 23:49:54',
            ],
            [
                'id' => 5,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Husniya Layliyana Ahwalik, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Bahasa Inggris',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => 'Sumursongo',
                'created_at' => '2026-07-14 23:51:45',
                'updated_at' => '2026-07-14 23:51:45',
            ],
            [
                'id' => 6,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Sudibya, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Konsentrasi Keahlian (DKV)',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-14 23:54:07',
                'updated_at' => '2026-07-14 23:54:07',
            ],
            [
                'id' => 7,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Riantiningsih, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Pendidikan Pancasila, Kreativitas Inovasi dan Kewirausahaan,',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-14 23:59:29',
                'updated_at' => '2026-07-15 00:01:10',
            ],
            [
                'id' => 8,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Reky Novianti, S.S',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Bahasa Inggris',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:00:46',
                'updated_at' => '2026-07-15 00:00:46',
            ],
            [
                'id' => 9,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Joko Setio Purwanto, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Projek Ilmu Pengetahuan Alam dan Sosial',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:02:40',
                'updated_at' => '2026-07-15 00:02:40',
            ],
            [
                'id' => 10,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Aditya Dwi Tamtomo, S.T',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Konsentrasi Keahlian (TSM), Kreativitas Inovasi dan Kewirausahaan (TSM)',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:06:02',
                'updated_at' => '2026-07-15 00:06:02',
            ],
            [
                'id' => 11,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Joko Prastiyo, S.T',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Dasar-dasar Teknik Sepeda Motor, Konsentrasi Keahlian (TSM), Mata Pelajaran Pilihan (TSM)',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:08:31',
                'updated_at' => '2026-07-15 00:08:31',
            ],
            [
                'id' => 12,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Viki Anggun Nur Wahyu, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Bahasa Indonesia',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:09:43',
                'updated_at' => '2026-07-15 00:09:43',
            ],
            [
                'id' => 13,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Mega Silvia Yulianti, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Bahasa Jawa, Seni Rupa',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:11:34',
                'updated_at' => '2026-07-15 00:12:04',
            ],
            [
                'id' => 14,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ayu Fitriana, S.Kom',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Dasar-dasar Desain Komunikasi Visual, Koding dan Kecerdasan Artifisial, Informatika',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:14:40',
                'updated_at' => '2026-07-15 00:14:40',
            ],
            [
                'id' => 15,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Muhammad Abdul Hamid',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Konsentrasi Keahlian (DKV), Mata Pelajaran Pilihan (DKV)',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:16:25',
                'updated_at' => '2026-07-16 07:12:06',
            ],
            [
                'id' => 16,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Arsyad Sayyudi Ali, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Pendidikan Agama dan Budi Pekerti, Pendidikan Jasmani Olahraga dan Kesehatan',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:18:41',
                'updated_at' => '2026-07-16 07:12:47',
            ],
            [
                'id' => 17,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Artika Wulandari, S.Pd',
                'kategori' => 'SMK',
                'mapel_bidang' => 'Matematika',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-15 00:19:42',
                'updated_at' => '2026-07-16 07:13:12',
            ],
            [
                'id' => 18,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'KH. Khoinuddin Yusuf',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Tafsir, Kaidah Fiqih',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:09:48',
                'updated_at' => '2026-07-16 07:13:31',
            ],
            [
                'id' => 19,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Hj. Laylatul Mubarokah',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Fiqih',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:14:02',
                'updated_at' => '2026-07-16 07:14:02',
            ],
            [
                'id' => 20,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Ahmad Fauzan',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Tauhid, Tarikh',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:15:17',
                'updated_at' => '2026-07-16 07:15:17',
            ],
            [
                'id' => 21,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Syamsi Syamsuddin',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Akhlaq, Hadist',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:15:48',
                'updated_at' => '2026-07-16 07:15:48',
            ],
            [
                'id' => 22,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Muhyiddin',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Ilmu Alat',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:16:18',
                'updated_at' => '2026-07-16 07:16:18',
            ],
            [
                'id' => 23,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => "Ust. Ahmad Mu'allim",
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Akhlaq',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:17:02',
                'updated_at' => '2026-07-16 07:17:02',
            ],
            [
                'id' => 24,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Ahmad Muhajir',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Fiqih, Hadist',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:18:05',
                'updated_at' => '2026-07-16 07:18:05',
            ],
            [
                'id' => 25,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Ahmad Jailani',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Aswaja',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:18:24',
                'updated_at' => '2026-07-16 07:18:24',
            ],
            [
                'id' => 26,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Purwanto Nuruddin',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Ilmu Alat, Faroidl',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:20:00',
                'updated_at' => '2026-07-16 07:20:50',
            ],
            [
                'id' => 27,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Istamaruddin',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Tarikh',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:20:31',
                'updated_at' => '2026-07-16 07:20:31',
            ],
            [
                'id' => 28,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Jawahirul Fawaid',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Kitabah, Akhlaq',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:21:23',
                'updated_at' => '2026-07-16 07:21:23',
            ],
            [
                'id' => 29,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ust. Farid Zainuddin',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Tauhid',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:21:54',
                'updated_at' => '2026-07-16 07:21:54',
            ],
            [
                'id' => 30,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ustdh. Bashirotin Linayli M.',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Fiqih, Ilmu Alat',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:22:43',
                'updated_at' => '2026-07-16 07:22:43',
            ],
            [
                'id' => 31,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ustdh. Arina Maqsurotin F.',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Ilmu Alat',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:23:20',
                'updated_at' => '2026-07-16 07:23:20',
            ],
            [
                'id' => 32,
                'foto' => 'guru/default.jpg',
                'nama_lengkap' => 'Ustdh. Alfiya Zahroul M.',
                'kategori' => 'Madrasah Diniyah',
                'mapel_bidang' => 'Tajwid',
                'pendidikan' => '-',
                'status' => 'Aktif',
                'alamat' => '-',
                'created_at' => '2026-07-16 07:23:45',
                'updated_at' => '2026-07-16 07:23:45',
            ],
        ];

        Guru::insert($gurus);
    }
}
