<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VirtualHotspotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('virtual_tour_hotspots')->insert([
            [
                'id' => 6,
                'virtual_tour_scene_id' => 4,
                'target_scene_id' => 5,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.0543,
                'pitch' => 0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-14 07:49:08',
                'updated_at' => '2026-07-15 17:58:24'
            ],
            [
                'id' => 7,
                'virtual_tour_scene_id' => 5,
                'target_scene_id' => 4,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => -1.2998,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 18:11:42',
                'updated_at' => '2026-07-15 18:53:41'
            ],
            [
                'id' => 8,
                'virtual_tour_scene_id' => 5,
                'target_scene_id' => 6,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.9000,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 18:27:50',
                'updated_at' => '2026-07-15 18:51:49'
            ],
            [
                'id' => 9,
                'virtual_tour_scene_id' => 6,
                'target_scene_id' => 7,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.3800,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 18:46:14',
                'updated_at' => '2026-07-15 19:00:25'
            ],
            [
                'id' => 10,
                'virtual_tour_scene_id' => 6,
                'target_scene_id' => 5,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => -0.7854,
                'pitch' => 0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-15 18:56:12',
                'updated_at' => '2026-07-15 19:00:02'
            ],
            [
                'id' => 11,
                'virtual_tour_scene_id' => 7,
                'target_scene_id' => 11,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 6.0214,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-15 19:05:17',
                'updated_at' => '2026-07-15 19:08:52'
            ],
            [
                'id' => 12,
                'virtual_tour_scene_id' => 7,
                'target_scene_id' => 9,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => -1.8326,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 19:10:17',
                'updated_at' => '2026-07-15 19:13:11'
            ],
            [
                'id' => 13,
                'virtual_tour_scene_id' => 7,
                'target_scene_id' => 6,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.2217,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 19:13:40',
                'updated_at' => '2026-07-15 19:14:53'
            ],
            [
                'id' => 14,
                'virtual_tour_scene_id' => 9,
                'target_scene_id' => 7,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => -1.6581,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 20:41:41',
                'updated_at' => '2026-07-15 20:42:35'
            ],
            [
                'id' => 15,
                'virtual_tour_scene_id' => 9,
                'target_scene_id' => 8,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.4486,
                'pitch' => 0.2618,
                'is_active' => 1,
                'created_at' => '2026-07-15 20:43:12',
                'updated_at' => '2026-07-15 20:44:49'
            ],
            [
                'id' => 16,
                'virtual_tour_scene_id' => 9,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Kantor SMK',
                'deskripsi' => 'Ruangan Guru - guru dan Kepala Sekolah SMK',
                'yaw' => 2.3562,
                'pitch' => 0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-15 20:50:07',
                'updated_at' => '2026-07-15 20:53:22'
            ],
            [
                'id' => 17,
                'virtual_tour_scene_id' => 9,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Kantor SMP',
                'deskripsi' => 'Ruangan Guru - guru dan Kepala Sekolah SMP',
                'yaw' => 3.1416,
                'pitch' => 0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-15 20:54:30',
                'updated_at' => '2026-07-15 20:54:56'
            ],
            [
                'id' => 18,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => 9,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.3963,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-15 20:57:10',
                'updated_at' => '2026-07-15 20:57:37'
            ],
            [
                'id' => 19,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => 19,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.6581,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-15 20:58:51',
                'updated_at' => '2026-07-15 21:00:34'
            ],
            [
                'id' => 20,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => 26,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.0718,
                'pitch' => -0.1222,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:01:18',
                'updated_at' => '2026-07-15 21:03:59'
            ],
            [
                'id' => 21,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Rumah Warga Sekitar',
                'deskripsi' => null,
                'yaw' => 5.2360,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:05:05',
                'updated_at' => '2026-07-15 21:05:33'
            ],
            [
                'id' => 22,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => 29,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.1888,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:06:55',
                'updated_at' => '2026-07-15 21:07:47'
            ],
            [
                'id' => 23,
                'virtual_tour_scene_id' => 26,
                'target_scene_id' => 8,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 6.1087,
                'pitch' => -0.0524,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:10:20',
                'updated_at' => '2026-07-15 21:10:48'
            ],
            [
                'id' => 24,
                'virtual_tour_scene_id' => 26,
                'target_scene_id' => 27,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.6109,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:11:59',
                'updated_at' => '2026-07-15 21:12:39'
            ],
            [
                'id' => 25,
                'virtual_tour_scene_id' => 27,
                'target_scene_id' => 28,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.4435,
                'pitch' => 0.1396,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:13:58',
                'updated_at' => '2026-07-15 21:26:50'
            ],
            [
                'id' => 26,
                'virtual_tour_scene_id' => 27,
                'target_scene_id' => 26,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.7525,
                'pitch' => 0.6981,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:15:48',
                'updated_at' => '2026-07-15 21:17:34'
            ],
            [
                'id' => 27,
                'virtual_tour_scene_id' => 28,
                'target_scene_id' => 27,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.6109,
                'pitch' => 0.1396,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:28:43',
                'updated_at' => '2026-07-15 21:29:22'
            ],
            [
                'id' => 28,
                'virtual_tour_scene_id' => 28,
                'target_scene_id' => 27,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.4105,
                'pitch' => 0.1571,
                'is_active' => 1,
                'created_at' => '2026-07-15 21:30:44',
                'updated_at' => '2026-07-15 21:31:43'
            ],
            [
                'id' => 29,
                'virtual_tour_scene_id' => 29,
                'target_scene_id' => 8,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.5236,
                'pitch' => 0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:01:30',
                'updated_at' => '2026-07-16 00:02:19'
            ],
            [
                'id' => 30,
                'virtual_tour_scene_id' => 29,
                'target_scene_id' => 30,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.5307,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:02:59',
                'updated_at' => '2026-07-16 00:04:08'
            ],
            [
                'id' => 31,
                'virtual_tour_scene_id' => 29,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Rumah Warga Sekitar',
                'deskripsi' => null,
                'yaw' => 4.0143,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:04:56',
                'updated_at' => '2026-07-16 00:05:45'
            ],
            [
                'id' => 32,
                'virtual_tour_scene_id' => 30,
                'target_scene_id' => 29,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.6981,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:06:59',
                'updated_at' => '2026-07-16 05:43:53'
            ],
            [
                'id' => 33,
                'virtual_tour_scene_id' => 30,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Koperasi',
                'deskripsi' => 'Koperasi pesantren menyediakan kebutuhan harian santri',
                'yaw' => 4.8869,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:09:04',
                'updated_at' => '2026-07-16 00:10:07'
            ],
            [
                'id' => 34,
                'virtual_tour_scene_id' => 30,
                'target_scene_id' => 32,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.9270,
                'pitch' => 0.1047,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:14:08',
                'updated_at' => '2026-07-16 00:16:05'
            ],
            [
                'id' => 35,
                'virtual_tour_scene_id' => 30,
                'target_scene_id' => 36,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.4034,
                'pitch' => 0.1047,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:16:59',
                'updated_at' => '2026-07-16 00:16:59'
            ],
            [
                'id' => 36,
                'virtual_tour_scene_id' => 32,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Tempat Wudhu Santri Putri',
                'deskripsi' => null,
                'yaw' => 4.9742,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:18:04',
                'updated_at' => '2026-07-16 00:20:05'
            ],
            [
                'id' => 37,
                'virtual_tour_scene_id' => 32,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'TK',
                'deskripsi' => null,
                'yaw' => 3.8397,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:21:24',
                'updated_at' => '2026-07-16 00:21:45'
            ],
            [
                'id' => 38,
                'virtual_tour_scene_id' => 32,
                'target_scene_id' => 34,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.7925,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:22:32',
                'updated_at' => '2026-07-16 00:22:32'
            ],
            [
                'id' => 39,
                'virtual_tour_scene_id' => 34,
                'target_scene_id' => 32,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.5708,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:23:34',
                'updated_at' => '2026-07-16 00:23:34'
            ],
            [
                'id' => 40,
                'virtual_tour_scene_id' => 34,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Ndalem Gus Umar',
                'deskripsi' => 'Rumah Kediaman Gus Umar',
                'yaw' => 3.8397,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:25:46',
                'updated_at' => '2026-07-16 00:26:16'
            ],
            [
                'id' => 41,
                'virtual_tour_scene_id' => 34,
                'target_scene_id' => 35,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.5379,
                'pitch' => 0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:27:14',
                'updated_at' => '2026-07-16 00:27:46'
            ],
            [
                'id' => 42,
                'virtual_tour_scene_id' => 35,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Dapur',
                'deskripsi' => 'Tempat memasak makanan untuk semua santri',
                'yaw' => 6.2832,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:28:53',
                'updated_at' => '2026-07-16 00:28:53'
            ],
            [
                'id' => 43,
                'virtual_tour_scene_id' => 35,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Pendopo belakang',
                'deskripsi' => 'Tempat makan santri putri',
                'yaw' => 3.3161,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:30:22',
                'updated_at' => '2026-07-16 00:30:40'
            ],
            [
                'id' => 44,
                'virtual_tour_scene_id' => 35,
                'target_scene_id' => 34,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.7453,
                'pitch' => 0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:31:24',
                'updated_at' => '2026-07-16 00:32:22'
            ],
            [
                'id' => 45,
                'virtual_tour_scene_id' => 32,
                'target_scene_id' => 30,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.7596,
                'pitch' => -0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:33:48',
                'updated_at' => '2026-07-16 00:37:52'
            ],
            [
                'id' => 46,
                'virtual_tour_scene_id' => 32,
                'target_scene_id' => 36,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.9341,
                'pitch' => -0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:37:15',
                'updated_at' => '2026-07-16 00:37:15'
            ],
            [
                'id' => 47,
                'virtual_tour_scene_id' => 36,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Dalem Ibu Nyai Hj Nurunasri',
                'deskripsi' => 'Rumah Kediaman Ibu Nyai Hj Nurunasri',
                'yaw' => 1.7453,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:40:28',
                'updated_at' => '2026-07-16 00:40:45'
            ],
            [
                'id' => 48,
                'virtual_tour_scene_id' => 36,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Kantor TQNS',
                'deskripsi' => 'Kantor Thoriqoh Qodiriyah Naqsyabandiyah',
                'yaw' => 1.7453,
                'pitch' => -0.8727,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:41:54',
                'updated_at' => '2026-07-16 00:42:06'
            ],
            [
                'id' => 49,
                'virtual_tour_scene_id' => 36,
                'target_scene_id' => 30,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.8798,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:42:41',
                'updated_at' => '2026-07-16 00:43:32'
            ],
            [
                'id' => 50,
                'virtual_tour_scene_id' => 36,
                'target_scene_id' => 37,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.1745,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:44:34',
                'updated_at' => '2026-07-16 00:45:32'
            ],
            [
                'id' => 51,
                'virtual_tour_scene_id' => 37,
                'target_scene_id' => 42,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.3562,
                'pitch' => 0.1222,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:47:10',
                'updated_at' => '2026-07-16 00:48:20'
            ],
            [
                'id' => 52,
                'virtual_tour_scene_id' => 37,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Asrama Santri Putri',
                'deskripsi' => 'Tempat tinggal santri putri',
                'yaw' => 3.3161,
                'pitch' => -0.2618,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:49:16',
                'updated_at' => '2026-07-16 00:49:44'
            ],
            [
                'id' => 53,
                'virtual_tour_scene_id' => 37,
                'target_scene_id' => 38,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.9599,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:51:30',
                'updated_at' => '2026-07-16 00:51:53'
            ],
            [
                'id' => 54,
                'virtual_tour_scene_id' => 37,
                'target_scene_id' => 43,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.6723,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:52:34',
                'updated_at' => '2026-07-16 00:53:20'
            ],
            [
                'id' => 55,
                'virtual_tour_scene_id' => 37,
                'target_scene_id' => 36,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.5379,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 00:54:04',
                'updated_at' => '2026-07-16 00:54:20'
            ],
            [
                'id' => 56,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Makam',
                'deskripsi' => 'Makah KH Syaifuddin Muhammad',
                'yaw' => 6.1087,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 01:51:59',
                'updated_at' => '2026-07-16 01:52:19'
            ],
            [
                'id' => 57,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Pendopo',
                'deskripsi' => 'Aula tempat kegiatan santri',
                'yaw' => 1.5708,
                'pitch' => -0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-16 01:53:20',
                'updated_at' => '2026-07-16 01:53:36'
            ],
            [
                'id' => 58,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => 39,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.5708,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 01:54:08',
                'updated_at' => '2026-07-16 01:54:08'
            ],
            [
                'id' => 59,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Asrama Santri Putra',
                'deskripsi' => 'Tempat tinggal santri putra',
                'yaw' => 0.6109,
                'pitch' => -0.4363,
                'is_active' => 1,
                'created_at' => '2026-07-16 01:56:12',
                'updated_at' => '2026-07-16 01:56:52'
            ],
            [
                'id' => 60,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => 40,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.6109,
                'pitch' => -0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 01:58:17',
                'updated_at' => '2026-07-16 01:58:52'
            ],
            [
                'id' => 61,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => 41,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.4435,
                'pitch' => -0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 01:59:17',
                'updated_at' => '2026-07-16 01:59:41'
            ],
            [
                'id' => 62,
                'virtual_tour_scene_id' => 39,
                'target_scene_id' => 38,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.5379,
                'pitch' => 0.2618,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:00:56',
                'updated_at' => '2026-07-16 02:02:12'
            ],
            [
                'id' => 63,
                'virtual_tour_scene_id' => 39,
                'target_scene_id' => 40,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 6.0214,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:03:17',
                'updated_at' => '2026-07-16 02:03:41'
            ],
            [
                'id' => 64,
                'virtual_tour_scene_id' => 39,
                'target_scene_id' => 41,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.7925,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:04:09',
                'updated_at' => '2026-07-16 02:04:50'
            ],
            [
                'id' => 65,
                'virtual_tour_scene_id' => 41,
                'target_scene_id' => 39,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.1745,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:06:08',
                'updated_at' => '2026-07-16 02:44:59'
            ],
            [
                'id' => 66,
                'virtual_tour_scene_id' => 41,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Asrama Santri Putra',
                'deskripsi' => 'Tempat tingal santri putra',
                'yaw' => 2.2689,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:07:29',
                'updated_at' => '2026-07-16 02:08:16'
            ],
            [
                'id' => 67,
                'virtual_tour_scene_id' => 41,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Ndalem KH Khoiruddin Yusuf',
                'deskripsi' => 'Rumah kediaman KH Khoiruddin Yusuf',
                'yaw' => 3.4383,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:16:58',
                'updated_at' => '2026-07-16 02:25:45'
            ],
            [
                'id' => 68,
                'virtual_tour_scene_id' => 41,
                'target_scene_id' => 38,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.2360,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:27:41',
                'updated_at' => '2026-07-16 02:27:57'
            ],
            [
                'id' => 69,
                'virtual_tour_scene_id' => 40,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Bengkel TSM',
                'deskripsi' => 'Tempat praktek siswa siswi SMK jurusan TSM',
                'yaw' => 3.1416,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:29:44',
                'updated_at' => '2026-07-16 02:29:57'
            ],
            [
                'id' => 70,
                'virtual_tour_scene_id' => 40,
                'target_scene_id' => 39,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.8469,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:30:38',
                'updated_at' => '2026-07-16 02:31:06'
            ],
            [
                'id' => 71,
                'virtual_tour_scene_id' => 40,
                'target_scene_id' => 38,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.6981,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:44:03',
                'updated_at' => '2026-07-16 02:44:03'
            ],
            [
                'id' => 72,
                'virtual_tour_scene_id' => 38,
                'target_scene_id' => 37,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.7997,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:46:17',
                'updated_at' => '2026-07-16 02:47:07'
            ],
            [
                'id' => 73,
                'virtual_tour_scene_id' => 42,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Kantor Yayasan',
                'deskripsi' => 'Kantor tempat pembayaran semu administrasi pondok pesantren',
                'yaw' => 3.2289,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 02:49:22',
                'updated_at' => '2026-07-16 02:50:25'
            ],
            [
                'id' => 74,
                'virtual_tour_scene_id' => 42,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Asrama Santri Putri',
                'deskripsi' => 'Tempat tinggal santri putri',
                'yaw' => 4.0143,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 03:01:15',
                'updated_at' => '2026-07-16 05:11:54'
            ],
            [
                'id' => 75,
                'virtual_tour_scene_id' => 42,
                'target_scene_id' => 37,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 6.1087,
                'pitch' => 0.4363,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:13:03',
                'updated_at' => '2026-07-16 05:14:13'
            ],
            [
                'id' => 76,
                'virtual_tour_scene_id' => 43,
                'target_scene_id' => 44,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.1416,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:21:24',
                'updated_at' => '2026-07-16 05:21:50'
            ],
            [
                'id' => 77,
                'virtual_tour_scene_id' => 43,
                'target_scene_id' => 45,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.0873,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:29:03',
                'updated_at' => '2026-07-16 05:30:33'
            ],
            [
                'id' => 79,
                'virtual_tour_scene_id' => 43,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Rumah Warga Sekitar',
                'deskripsi' => null,
                'yaw' => 1.3963,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:31:33',
                'updated_at' => '2026-07-16 05:31:51'
            ],
            [
                'id' => 80,
                'virtual_tour_scene_id' => 43,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Tempan Penyimpanan Kitab',
                'deskripsi' => null,
                'yaw' => 5.4105,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:33:43',
                'updated_at' => '2026-07-16 05:34:07'
            ],
            [
                'id' => 81,
                'virtual_tour_scene_id' => 43,
                'target_scene_id' => 38,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.5379,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:35:04',
                'updated_at' => '2026-07-16 05:35:17'
            ],
            [
                'id' => 82,
                'virtual_tour_scene_id' => 45,
                'target_scene_id' => 43,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.0873,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:36:10',
                'updated_at' => '2026-07-16 05:36:41'
            ],
            [
                'id' => 83,
                'virtual_tour_scene_id' => 45,
                'target_scene_id' => 37,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.2618,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:37:04',
                'updated_at' => '2026-07-16 05:37:04'
            ],
            [
                'id' => 84,
                'virtual_tour_scene_id' => 45,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Kolah',
                'deskripsi' => 'Tempat wudhu santri putra',
                'yaw' => 2.2689,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:38:00',
                'updated_at' => '2026-07-16 05:38:22'
            ],
            [
                'id' => 85,
                'virtual_tour_scene_id' => 45,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Asrama Santri Putra',
                'deskripsi' => 'Tempat tinggal santri putra',
                'yaw' => 3.4907,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:39:43',
                'updated_at' => '2026-07-16 05:39:57'
            ],
            [
                'id' => 86,
                'virtual_tour_scene_id' => 45,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Kamar Mandi Putra',
                'deskripsi' => null,
                'yaw' => 5.0615,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:40:52',
                'updated_at' => '2026-07-16 05:41:22'
            ],
            [
                'id' => 87,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => "SMK Ma'arif",
                'deskripsi' => "Gedung SMK Ma'arif Darus Sholihin",
                'yaw' => 2.0944,
                'pitch' => -0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:45:39',
                'updated_at' => '2026-07-16 05:45:39'
            ],
            [
                'id' => 88,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => "Masjid Jami' Imaduddin",
                'deskripsi' => null,
                'yaw' => 3.0718,
                'pitch' => -0.5236,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:48:14',
                'updated_at' => '2026-07-16 05:48:14'
            ],
            [
                'id' => 89,
                'virtual_tour_scene_id' => 8,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => 'Lab DKV',
                'deskripsi' => 'Tempat praktek siswa siswi SMK jurusan DKV',
                'yaw' => 2.3562,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:50:04',
                'updated_at' => '2026-07-16 05:51:38'
            ],
            [
                'id' => 90,
                'virtual_tour_scene_id' => 19,
                'target_scene_id' => 20,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.7525,
                'pitch' => -0.2269,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:53:11',
                'updated_at' => '2026-07-16 05:54:08'
            ],
            [
                'id' => 91,
                'virtual_tour_scene_id' => 19,
                'target_scene_id' => 8,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.1015,
                'pitch' => 0.6981,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:54:41',
                'updated_at' => '2026-07-16 05:55:15'
            ],
            [
                'id' => 92,
                'virtual_tour_scene_id' => 20,
                'target_scene_id' => 19,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.1345,
                'pitch' => 0.5236,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:57:21',
                'updated_at' => '2026-07-16 05:58:09'
            ],
            [
                'id' => 93,
                'virtual_tour_scene_id' => 20,
                'target_scene_id' => 22,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.1345,
                'pitch' => -0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:58:54',
                'updated_at' => '2026-07-16 05:59:08'
            ],
            [
                'id' => 94,
                'virtual_tour_scene_id' => 20,
                'target_scene_id' => 21,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.8798,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 05:59:57',
                'updated_at' => '2026-07-16 06:00:12'
            ],
            [
                'id' => 95,
                'virtual_tour_scene_id' => 21,
                'target_scene_id' => 20,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.4363,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:01:03',
                'updated_at' => '2026-07-16 06:01:24'
            ],
            [
                'id' => 96,
                'virtual_tour_scene_id' => 22,
                'target_scene_id' => 23,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.1416,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:02:27',
                'updated_at' => '2026-07-16 06:02:56'
            ],
            [
                'id' => 97,
                'virtual_tour_scene_id' => 22,
                'target_scene_id' => 20,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.4034,
                'pitch' => 0.8727,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:03:37',
                'updated_at' => '2026-07-16 06:04:14'
            ],
            [
                'id' => 98,
                'virtual_tour_scene_id' => 23,
                'target_scene_id' => 22,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.2360,
                'pitch' => 0.5236,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:05:06',
                'updated_at' => '2026-07-16 06:06:41'
            ],
            [
                'id' => 99,
                'virtual_tour_scene_id' => 23,
                'target_scene_id' => 25,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.2217,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:07:26',
                'updated_at' => '2026-07-16 06:07:26'
            ],
            [
                'id' => 100,
                'virtual_tour_scene_id' => 25,
                'target_scene_id' => 23,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.8397,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:08:12',
                'updated_at' => '2026-07-16 06:08:26'
            ],
            [
                'id' => 101,
                'virtual_tour_scene_id' => 7,
                'target_scene_id' => null,
                'tipe' => 'information',
                'icon' => 'info',
                'judul' => "SMP Ma'arif",
                'deskripsi' => "Gedung SMP Ma'arif Darus Sholihin",
                'yaw' => 6.0214,
                'pitch' => -0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:11:05',
                'updated_at' => '2026-07-16 06:11:05'
            ],
            [
                'id' => 102,
                'virtual_tour_scene_id' => 11,
                'target_scene_id' => 7,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.3963,
                'pitch' => -0.0349,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:12:13',
                'updated_at' => '2026-07-16 06:12:36'
            ],
            [
                'id' => 103,
                'virtual_tour_scene_id' => 11,
                'target_scene_id' => 12,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.9742,
                'pitch' => -0.2618,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:13:11',
                'updated_at' => '2026-07-16 06:13:43'
            ],
            [
                'id' => 104,
                'virtual_tour_scene_id' => 12,
                'target_scene_id' => 11,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.9199,
                'pitch' => 0.4363,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:14:26',
                'updated_at' => '2026-07-16 06:15:23'
            ],
            [
                'id' => 105,
                'virtual_tour_scene_id' => 12,
                'target_scene_id' => 15,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 2.6180,
                'pitch' => -0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:16:06',
                'updated_at' => '2026-07-16 06:16:35'
            ],
            [
                'id' => 106,
                'virtual_tour_scene_id' => 12,
                'target_scene_id' => 14,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.0543,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:17:40',
                'updated_at' => '2026-07-16 06:18:28'
            ],
            [
                'id' => 107,
                'virtual_tour_scene_id' => 14,
                'target_scene_id' => 12,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 6.1087,
                'pitch' => 0.1745,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:19:07',
                'updated_at' => '2026-07-16 06:19:07'
            ],
            [
                'id' => 108,
                'virtual_tour_scene_id' => 14,
                'target_scene_id' => 13,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.8869,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:20:43',
                'updated_at' => '2026-07-16 06:21:00'
            ],
            [
                'id' => 109,
                'virtual_tour_scene_id' => 13,
                'target_scene_id' => 14,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 4.0143,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:22:08',
                'updated_at' => '2026-07-16 06:23:11'
            ],
            [
                'id' => 110,
                'virtual_tour_scene_id' => 15,
                'target_scene_id' => 12,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.7596,
                'pitch' => 0.6981,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:24:24',
                'updated_at' => '2026-07-16 06:24:43'
            ],
            [
                'id' => 111,
                'virtual_tour_scene_id' => 15,
                'target_scene_id' => 16,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 0.5236,
                'pitch' => -0.3491,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:25:32',
                'updated_at' => '2026-07-16 06:25:42'
            ],
            [
                'id' => 112,
                'virtual_tour_scene_id' => 16,
                'target_scene_id' => 15,
                'tipe' => 'navigation',
                'icon' => 'arrow-right',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 6.1087,
                'pitch' => 0.6981,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:26:24',
                'updated_at' => '2026-07-16 06:26:39'
            ],
            [
                'id' => 113,
                'virtual_tour_scene_id' => 16,
                'target_scene_id' => 17,
                'tipe' => 'navigation',
                'icon' => 'arrow-up',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 1.1345,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:27:35',
                'updated_at' => '2026-07-16 06:28:04'
            ],
            [
                'id' => 114,
                'virtual_tour_scene_id' => 17,
                'target_scene_id' => 16,
                'tipe' => 'navigation',
                'icon' => 'arrow-left',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.0615,
                'pitch' => 0.5236,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:29:09',
                'updated_at' => '2026-07-16 06:29:25'
            ],
            [
                'id' => 115,
                'virtual_tour_scene_id' => 17,
                'target_scene_id' => 18,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 3.7525,
                'pitch' => -0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:29:49',
                'updated_at' => '2026-07-16 06:30:50'
            ],
            [
                'id' => 116,
                'virtual_tour_scene_id' => 18,
                'target_scene_id' => 17,
                'tipe' => 'navigation',
                'icon' => 'door',
                'judul' => null,
                'deskripsi' => null,
                'yaw' => 5.9865,
                'pitch' => 0.0873,
                'is_active' => 1,
                'created_at' => '2026-07-16 06:31:46',
                'updated_at' => '2026-07-16 06:32:25'
            ],
        ]);
    }
}