<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VirtualScaneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $scenes = [
            [
                'id' => 4,
                'nama_lokasi' => 'Gerbang Utama',
                'slug' => 'gerbang-utama',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 1,
                'is_start_scene' => 1,
                'show_on_landing' => 1,
                'created_at' => '2026-07-02 01:44:21',
                'updated_at' => '2026-07-12 00:34:22',
            ],
            [
                'id' => 5,
                'nama_lokasi' => 'Jalan1',
                'slug' => 'jalan1',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 2,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 07:40:45',
                'updated_at' => '2026-07-16 06:33:14',
            ],
            [
                'id' => 6,
                'nama_lokasi' => 'Jalan2',
                'slug' => 'jalan2',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 3,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 07:41:23',
                'updated_at' => '2026-07-16 06:33:20',
            ],
            [
                'id' => 7,
                'nama_lokasi' => 'Jalan3',
                'slug' => 'jalan3',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 4,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 07:42:33',
                'updated_at' => '2026-07-16 06:33:25',
            ],
            [
                'id' => 8,
                'nama_lokasi' => 'Depan Masjid',
                'slug' => 'depan-masjid',
                'deskripsi' => null,
                'thumbnail' => 'field',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 6,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 07:44:51',
                'updated_at' => '2026-07-16 06:33:38',
            ],
            [
                'id' => 9,
                'nama_lokasi' => 'Jalan4',
                'slug' => 'jalan4',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 5,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:28:48',
                'updated_at' => '2026-07-16 06:33:30',
            ],
            [
                'id' => 11,
                'nama_lokasi' => 'Pintu Masuk SMP',
                'slug' => 'pintu-masuk-smp',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 7,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:31:20',
                'updated_at' => '2026-07-16 06:33:50',
            ],
            [
                'id' => 12,
                'nama_lokasi' => 'SMP Lantai 2',
                'slug' => 'smp-lantai-2',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 8,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:33:12',
                'updated_at' => '2026-07-16 06:33:45',
            ],
            [
                'id' => 13,
                'nama_lokasi' => 'Ruang Kelas SMP Lantai 2',
                'slug' => 'ruang-kelas-smp-lantai-2',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 10,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:35:13',
                'updated_at' => '2026-07-16 06:34:06',
            ],
            [
                'id' => 14,
                'nama_lokasi' => 'Jalan SMP Lantai 2',
                'slug' => 'jalan-smp-lantai-2',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 9,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:36:22',
                'updated_at' => '2026-07-16 06:33:57',
            ],
            [
                'id' => 15,
                'nama_lokasi' => 'Tangga SMP Lantai 3',
                'slug' => 'tangga-smp-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 11,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:38:41',
                'updated_at' => '2026-07-16 06:34:11',
            ],
            [
                'id' => 16,
                'nama_lokasi' => 'SMP Lantai 3',
                'slug' => 'smp-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 12,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:39:25',
                'updated_at' => '2026-07-16 06:34:18',
            ],
            [
                'id' => 17,
                'nama_lokasi' => 'Jalan SMP lantai 3',
                'slug' => 'jalan-smp-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 13,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:39:59',
                'updated_at' => '2026-07-16 06:34:28',
            ],
            [
                'id' => 18,
                'nama_lokasi' => 'Ruang Kelas SMP Lantai 3',
                'slug' => 'ruang-kelas-smp-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 14,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:40:37',
                'updated_at' => '2026-07-16 06:34:36',
            ],
            [
                'id' => 19,
                'nama_lokasi' => 'Pintu Masuk SMK',
                'slug' => 'pintu-masuk-smk',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 15,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:42:40',
                'updated_at' => '2026-07-16 06:34:42',
            ],
            [
                'id' => 20,
                'nama_lokasi' => 'SMK Lantai 2',
                'slug' => 'smk-lantai-2',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 16,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:43:38',
                'updated_at' => '2026-07-16 06:34:51',
            ],
            [
                'id' => 21,
                'nama_lokasi' => 'Ruang Kelas SMK Lantai 2',
                'slug' => 'ruang-kelas-smk-lantai-2',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 17,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:44:38',
                'updated_at' => '2026-07-16 06:35:00',
            ],
            [
                'id' => 22,
                'nama_lokasi' => 'Tangga SMK Lantai 3',
                'slug' => 'tangga-smk-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 18,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:45:48',
                'updated_at' => '2026-07-16 06:35:11',
            ],
            [
                'id' => 23,
                'nama_lokasi' => 'SMK Lantai 3',
                'slug' => 'smk-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 19,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:47:18',
                'updated_at' => '2026-07-16 06:35:27',
            ],
            [
                'id' => 25,
                'nama_lokasi' => 'Ruang Kelas SMK Lantai 3',
                'slug' => 'ruang-kelas-smk-lantai-3',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 20,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 08:48:12',
                'updated_at' => '2026-07-16 06:35:18',
            ],
            [
                'id' => 26,
                'nama_lokasi' => 'Masjid Bawah',
                'slug' => 'masjid-bawah',
                'deskripsi' => null,
                'thumbnail' => 'mosque',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 21,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:06:19',
                'updated_at' => '2026-07-16 06:35:40',
            ],
            [
                'id' => 27,
                'nama_lokasi' => 'Tangga Masjid',
                'slug' => 'tangga-masjid',
                'deskripsi' => null,
                'thumbnail' => 'mosque',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 22,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:06:48',
                'updated_at' => '2026-07-16 06:35:51',
            ],
            [
                'id' => 28,
                'nama_lokasi' => 'Masjid Atas',
                'slug' => 'masjid-atas',
                'deskripsi' => null,
                'thumbnail' => 'mosque',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 23,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:07:23',
                'updated_at' => '2026-07-16 06:36:09',
            ],
            [
                'id' => 29,
                'nama_lokasi' => 'Jalan Samping Masjid',
                'slug' => 'jalan-samping-masjid',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 24,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:13:37',
                'updated_at' => '2026-07-16 06:36:19',
            ],
            [
                'id' => 30,
                'nama_lokasi' => 'Koperasi',
                'slug' => 'koperasi',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 25,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:15:26',
                'updated_at' => '2026-07-16 06:36:30',
            ],
            [
                'id' => 31,
                'nama_lokasi' => 'Jalan Samping Masjid 2',
                'slug' => 'jalan-samping-masjid-2',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'draft',
                'urutan' => 26,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:16:30',
                'updated_at' => '2026-07-14 23:16:30',
            ],
            [
                'id' => 32,
                'nama_lokasi' => 'Depan TK',
                'slug' => 'depan-tk',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 27,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:18:56',
                'updated_at' => '2026-07-16 06:36:39',
            ],
            [
                'id' => 34,
                'nama_lokasi' => 'Samping Ndalem Gus Umar',
                'slug' => 'samping-ndalem-gus-umar',
                'deskripsi' => null,
                'thumbnail' => 'road',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 28,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:22:15',
                'updated_at' => '2026-07-16 06:36:47',
            ],
            [
                'id' => 35,
                'nama_lokasi' => 'Dapur',
                'slug' => 'dapur',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 29,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:22:51',
                'updated_at' => '2026-07-16 06:37:00',
            ],
            [
                'id' => 36,
                'nama_lokasi' => 'Ndalem Bu Nyai Sepuh',
                'slug' => 'ndalem-bu-nyai-sepuh',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 30,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:23:55',
                'updated_at' => '2026-07-16 06:37:10',
            ],
            [
                'id' => 37,
                'nama_lokasi' => 'Barat Ndalem Timur',
                'slug' => 'barat-ndalem-timur',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 31,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:27:06',
                'updated_at' => '2026-07-16 06:37:19',
            ],
            [
                'id' => 38,
                'nama_lokasi' => 'Lapangan Upacara',
                'slug' => 'lapangan-upacara',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 32,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:27:52',
                'updated_at' => '2026-07-16 06:37:28',
            ],
            [
                'id' => 39,
                'nama_lokasi' => 'Pendopo',
                'slug' => 'pendopo',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 33,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:28:23',
                'updated_at' => '2026-07-16 06:37:36',
            ],
            [
                'id' => 40,
                'nama_lokasi' => 'Selatan Pendopo',
                'slug' => 'selatan-pendopo',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 34,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:29:24',
                'updated_at' => '2026-07-16 06:37:49',
            ],
            [
                'id' => 41,
                'nama_lokasi' => 'Utara Pendopo',
                'slug' => 'utara-pendopo',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 35,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:30:37',
                'updated_at' => '2026-07-16 06:37:58',
            ],
            [
                'id' => 42,
                'nama_lokasi' => 'Depan Kantor Yayasan',
                'slug' => 'depan-kantor-yayasan',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 36,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:31:40',
                'updated_at' => '2026-07-16 06:38:17',
            ],
            [
                'id' => 43,
                'nama_lokasi' => 'Depan Makam',
                'slug' => 'depan-makam',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 37,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:32:53',
                'updated_at' => '2026-07-16 06:38:24',
            ],
            [
                'id' => 44,
                'nama_lokasi' => 'Makam',
                'slug' => 'makam',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 36,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:33:33',
                'updated_at' => '2026-07-16 06:38:09',
            ],
            [
                'id' => 45,
                'nama_lokasi' => 'Kolah',
                'slug' => 'kolah',
                'deskripsi' => null,
                'thumbnail' => 'building',
                'panorama' => 'virtual-tour/panoramas/default.jpg',
                'status' => 'published',
                'urutan' => 39,
                'is_start_scene' => 0,
                'show_on_landing' => 0,
                'created_at' => '2026-07-14 23:34:23',
                'updated_at' => '2026-07-16 06:38:33',
            ],
        ];

        DB::table('virtual_tour_scenes')->insert($scenes);
    }
}